POST https://node-do-zero-ds6u.onrender.com/videos
Content-Type: application/json

{
    "title": "Vídeo 02",
    "description": "Esse é o segundo vídeo",
    "duration": 180 
}

### // Isso é um divisor de rotas

GET https://node-do-zero-ds6u.onrender.com/videos

###

PUT https://node-do-zero-ds6u.onrender.com/videos/5bff4d76-85cd-4b2c-9369-83f11fd348b9
Content-Type: application/json

{
    "title": "Vídeo 02",
    "description": "Esse é o segundo vídeo",
    "duration": 185
}

###

DELETE https://node-do-zero-ds6u.onrender.com/videos/8dd4c07b-01b5-4875-9e32-29ae74b8772b
